import type { Metadata } from "next";
import Image from "next/image";
import "./main.css";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="geist-font min-h-full flex flex-col">
        <nav className="p-4">
          {/* Image Logo */}
          <div className="relative w-36 h-36">
            <Link href="/">
            <Image 
              src="/logo/nexus-logo.png" 
              alt="Nexus Logo"
              fill
              className=""></Image>
            </Link>
              </div>
              <ul className="flex gap-x-4">
                <li className="list-none group">
                  <Link href="/features">Features</Link>
                  <div className="w-0 h-0.5 bg-primary-300 transition-all duration-500 group-hover:w-full"></div>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>
                  <Link href="/contact">Contact</Link>
                </li>
              </ul>
              </nav>
        {children}
        </body>
    </html>
  );
}
