import type { Metadata } from "next";
import Image from "next/image";
import "./main.css";
import { ChevronDown, House, X } from "lucide-react";
import Link from "next/link";
import Navbar from "./components/baseComponents/Navbar";
import Footer from "./components/baseComponents/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="geist-font min-h-full flex flex-col bg-background-50">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
